### ISSUE TITLE
Rendering with partials?

### ISSUE THREAD

**Issue by teeg82** [paulspringett/csv_shaper#22]
Unless I'm completely blind, I cannot seem to find a way to render partials from a csv.shaper template. A simple example would have the parent template containing a line like

    render "invoices/csv/calls_summary"

with a file in that directory called `calls_summary.csv.shaper`. However when I try to render, I get the error message

    you must define some headers using csv.headers ...

Am I missing or misunderstanding something?

**Comment by paulspringett** [comment]
Hey @teeg82 sorry but there's not currently support for Rails partial rendering within `.csv.shaper` files. 

Adding support for this is tricky because currently the contents of the `CSVShaper.encode` block (and therefore the Rails view template) are framework agnostic and introducing a `render` method would tie the DSL to Rails only.

Can you achieve what you're aiming to do without partials?

**Comment by teeg82** [comment]
Sorry for the delay in replying. I understand completely, thanks for the explanation. My monkey rails-brain has a weird tendency to think every gem is made with rails support, for some reason. 

Yeah I was able to do it by basically just copy+pasting the common bits across the different templates. I had a lot of templates, which is why I thought a partial would make things much easier, but I don't think they're likely to change much if at all in the future, so in this case at least it shouldn't present a major problem.

Thanks for your help. Love the gem.
